# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Setup Github Actions Environment"
  lane :gha_setup do
    keychain_password = SecureRandom.uuid
    create_keychain(
      name: "ios-build.keychain",
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )
    import_certificate(
      certificate_path: ENV["IOS_CERTIFICATE_FILE"],
      certificate_password: ENV["SIGNING_KEY_P12_PASSWORD"],
      keychain_name: "ios-build.keychain",
      keychain_password: keychain_password,
      log_output: true
    )
  end

  desc "Create a beta build"
  lane :beta_build do
    if ENV['BUILD_VERSION']
        vmat = /v(?<version>\d+.\d+.\d+).(?<build>\d+).*/.match(ENV["BUILD_VERSION"])        
        raise "Bad build version" if vmat.nil?

        build_version = vmat[:version]
        build_number = vmat[:build].to_i
        increment_version_number(xcodeproj: ENV['XCODEPROJ'], version_number: build_version)
        increment_build_number(xcodeproj: ENV['XCODEPROJ'], build_number: build_number)
    else
        increment_build_number(xcodeproj: ENV['XCODEPROJ'])
    end

    build_app(workspace: ENV['WORKSPACE'], scheme: ENV['SCHEME'])
  end

  desc "Push a new beta build to TestFlight"
  lane :beta_release do
    upload_to_testflight
  end
end
