# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Create new Internal Track Build"
  lane :internal_build do
    increment_version_code(
      gradle_file_path: "app/build.gradle",
    )

    gradle(task: "clean bundle build", build_type: "Release")
  end

  desc "Deploy a new Internal Track Build to Google Play"
  lane :internal_release do
    gradle(task: "bundle", build_type: "Release")

    upload_to_play_store(
      track: "internal",
      skip_upload_apk: true,
      release_status: "draft"
    )
  end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   increment_version_code(
  #     gradle_file_path: "app/build.gradle",
  #   )
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
