name: iOS

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Node Setup
      uses: actions/setup-node@v1

    - name: Install Dependencies
      run: yarn install

    - name: Update Pods
      run: |
        gem update cocoapods xcodeproj
        cd ios && pod install && cd ..

    - run: brew tap wix/brew
    - run: brew install applesimutils
    - run: yarn pre:test:ios
    - run: yarn test:ios

